name: py-stack-linter
description: A composite linter action for Python projects - runs Ruff, file structure checks, and Dockerfile validation
author: ross412
branding:
  icon: check-circle
  color: blue

inputs:
  python-version:
    description: Python version to use for linting
    required: false
    default: "3.11"
  ruff-version:
    description: Ruff version to use (or "latest")
    required: false
    default: "latest"
  run-structure-lint:
    description: Enable file structure linting
    required: false
    default: "true"
  run-dockerfile-lint:
    description: Enable Dockerfile linting
    required: false
    default: "true"
  trusted-registries:
    description: Comma-separated list of extra trusted registries for hadolint
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Normalize shared scripts to LF
      shell: bash
      run: |
        sed -i 's/\r$//' "${{ github.action_path }}/scripts/structure-lint.sh"
        sed -i 's/\r$//' "${{ github.action_path }}/scripts/*.sh" || true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run Ruff (using shared config)
      id: ruff
      uses: astral-sh/ruff-action@v3
      continue-on-error: true
      with:
        version: ${{ inputs.ruff-version }}
        args: check --config ${{ github.action_path }}/ruff.toml

    - name: File structure lint
      id: structure
      if: ${{ inputs.run-structure-lint == 'true' }}
      continue-on-error: true
      shell: bash
      run: bash "${{ github.action_path }}/scripts/structure-lint.sh"

    - name: Build Hadolint config
      id: build-hadolint-config
      if: ${{ inputs.run-dockerfile-lint == 'true' }}
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail
        cp "${{ github.action_path }}/.hadolint.yaml" "${{ runner.temp }}/hadolint.generated.yaml"

        echo "" >> "${{ runner.temp }}/hadolint.generated.yaml"
        echo "trustedRegistries:" >> "${{ runner.temp }}/hadolint.generated.yaml"
        echo "  - docker.io" >> "${{ runner.temp }}/hadolint.generated.yaml"
        echo "  - ghcr.io" >> "${{ runner.temp }}/hadolint.generated.yaml"

        if [ -n "${{ inputs.trusted-registries }}" ]; then
          IFS=',' read -ra REGS <<< "${{ inputs.trusted-registries }}"
          for r in "${REGS[@]}"; do
            r="$(echo "$r" | xargs)"
            [ -n "$r" ] && echo "  - $r" >> "${{ runner.temp }}/hadolint.generated.yaml"
          done
        fi

    - name: Hadolint (Dockerfile lint)
      id: hadolint
      if: ${{ inputs.run-dockerfile-lint == 'true' }}
      uses: hadolint/hadolint-action@v3.1.0
      continue-on-error: true
      with:
        dockerfile: Dockerfile
        recursive: true
        config: ${{ runner.temp }}/hadolint.generated.yaml

    - name: Fail if any linter failed
      if: always()
      shell: bash
      run: |
        ruff_failed=0
        structure_failed=0
        hadolint_failed=0

        if [ "${{ steps.ruff.outcome }}" != "success" ] && [ "${{ steps.ruff.outcome }}" != "skipped" ]; then
          echo "Ruff linting failed."
          ruff_failed=1
        fi

        if [ "${{ steps.structure.outcome }}" != "success" ] && [ "${{ steps.structure.outcome }}" != "skipped" ]; then
          echo "Structure linting failed."
          structure_failed=1
        fi

        if [ "${{ steps.hadolint.outcome }}" != "success" ] && [ "${{ steps.hadolint.outcome }}" != "skipped" ]; then
          echo "Hadolint failed."
          hadolint_failed=1
        fi

        if [ $ruff_failed -eq 1 ] || [ $structure_failed -eq 1 ] || [ $hadolint_failed -eq 1 ]; then
          exit 1
        fi
